os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
env: SWIFT_VERSION=5.0.1
osx_image: xcode10.2
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
  - swift test