matrix:
  include:
    - os: linux
      dist: trusty
      language: swift
      install:
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      sudo: required
      env: SWIFT_VERSION=5.0.1
    - os: osx
      osx_image: xcode10.2
      language: swift

script:
  - swift build