env: SWIFT_VERSION=5.0.1
language: Swift

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      install:
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      script:
        - swift build
    - os: osx
      osx_image: xcode10.2